services:
  backend:
    build:
      context: ./backend
    container_name: questmetrix-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:8
    container_name: questmetrix-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16.15
    container_name: questmetrix-postgres
    environment:
      POSTGRES_DB: questmetrix
      POSTGRES_USER: questmetrix
      POSTGRES_PASSWORD: questmetrix
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build:
      context: ./backend
    container_name: questmetrix-worker
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    command: ["python", "worker.py"]

  test-runner:
    build:
      context: ./backend
    container_name: questmetrix-test-runner
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - postgres
      - redis

    # docker compose --profile test up --build test-runner
    profiles:
      - test 
      
    # Run only integration and e2e folders
    command: ["python", "-m", "pytest", "tests/integration", "tests/e2e"]

volumes:
  postgres_data:
